defmodule BuildFixer do
  def run do
    asm_dir = "native/fp_lib/src/asm"
    files = File.ls!(asm_dir)
            |> Enum.filter(&String.ends_with?(&1, ".asm"))
    
    # Generate Object rules
    obj_rules = Enum.map(files, fn file ->
      obj_name = String.replace(file, ".asm", ".obj")
      """
native/#{obj_name}: #{asm_dir}/#{file}
	nasm -f win64 #{asm_dir}/#{file} -o native/#{obj_name}
      """
    end) |> Enum.join("\n")
    
    objs = Enum.map(files, fn file -> "native/" <> String.replace(file, ".asm", ".obj") end) |> Enum.join(" ")

    makefile_content = """
# Makefile for Windows (using MinGW/GCC + NASM)
# AUTOMATICALLY GENERATED BY fix_build.exs

NIF_SRC = native/merkle_nif.c
PRIV_DIR = priv
DLL_OUT = $(PRIV_DIR)/merkle_nif.dll

# Compiler Flags
CFLAGS = -O3 -std=c11 -Wall -shared
# Includes for Erlang NIF headers (Elixir Make sets ERL_EI_INCLUDE_DIR)
# Also include fp_lib headers
INCLUDES = -I\"$(ERL_EI_INCLUDE_DIR)\" -Inative -Inative/fp_lib/include

all: $(PRIV_DIR) $(DLL_OUT)

$(PRIV_DIR):
	if not exist $(PRIV_DIR) mkdir $(PRIV_DIR)

# 1. Compile Assembly to Object files
#{obj_rules}

# 2. Link C NIF + ASM Objects into DLL
$(DLL_OUT): #{objs} $(NIF_SRC)
	gcc $(CFLAGS) $(INCLUDES) -o $(DLL_OUT) $(NIF_SRC) #{objs}

clean:
	del native\*.obj
	del priv\*.dll
""
    File.write!("Makefile", makefile_content)
    IO.puts "Generated Makefile with #{length(files)} ASM files."
  end
end

BuildFixer.run()
