#include <string.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

// --- GCC 14/15 COMPATIBILITY HACK ---
#ifdef __GNUC__
  #define _SAVED_GNUC_ __GNUC__
  #undef __GNUC__
#endif

#include <erl_nif.h>

#ifdef _SAVED_GNUC_
  #define __GNUC__ _SAVED_GNUC_
  #undef _SAVED_GNUC_
#endif

// --- INCLUDE THE AUTOMATICALLY GENERATED NIF IMPLEMENTATION ---
// This file is generated by 'mix run gen_bridge.exs' and contains
// all the nif_fp_* wrapper functions and the generated_nif_funcs array.
#include "generated_nif.c"

// --- LIFECYCLE ---

static int load(ErlNifEnv* env, void** priv_data, ERL_NIF_TERM load_info) {
    return load_resources(env, priv_data, load_info);
}

// We use the array from generated_nif.c
ERL_NIF_INIT(Elixir.MerkleDb.ASM, generated_nif_funcs, load, NULL, NULL, NULL)
