#include <string.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

// --- GCC 14/15 COMPATIBILITY HACK ---
#ifdef __GNUC__
  #define _SAVED_GNUC_ __GNUC__
  #undef __GNUC__
#endif

#include <erl_nif.h>

#ifdef _SAVED_GNUC_
  #define __GNUC__ _SAVED_GNUC_
  #undef _SAVED_GNUC_
#endif

// --- INCLUDE QUERY KERNEL ---
#include "fp_lib/include/fp_query.h"
#include "fp_lib/include/fp_hnsw.h"

// --- INCLUDE BLAKE3 ---
#include "fp_lib/include/fp_blake3.h"

// --- INCLUDE MMAP WRAPPER ---
#include "fp_lib/include/fp_mmap.h"
#include "fp_lib/include/fp_bitmap.h"

// Forward declarations for manual NIFs used in generated_nif.c
static ERL_NIF_TERM manual_nif_fp_query_gemv_columnar(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]);
static ERL_NIF_TERM manual_nif_fp_query_gemv_columnar_batch(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]);
static ERL_NIF_TERM manual_nif_fp_query_gemv_f32_batch(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]);
static ERL_NIF_TERM manual_nif_fp_vector_sum_f32(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]);
static ERL_NIF_TERM manual_nif_fp_query_gemv_quantized_f32(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]);
static ERL_NIF_TERM manual_nif_fp_mmap_open(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]);
static ERL_NIF_TERM manual_nif_fp_query_gemv_mmap_f32(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]);
static ERL_NIF_TERM manual_nif_fp_query_gemv_bitmasked_f32(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]);
static ERL_NIF_TERM manual_nif_fp_bitmap_set(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]);
static ERL_NIF_TERM manual_nif_fp_bitmap_and(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]);
static ERL_NIF_TERM nif_fp_blake3_hash(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]);

// --- INCLUDE THE AUTOMATICALLY GENERATED NIF IMPLEMENTATION ---
// This file is generated by 'mix run gen_bridge.exs' and contains
// all the nif_fp_* wrapper functions and the generated_nif_funcs array.
#include "generated_nif.c"
#include "fp_job_nif.c"

// --- HNSW RESOURCE MANAGEMENT ---

static ErlNifResourceType* HNSW_RES_TYPE = NULL;
static ErlNifResourceType* RES_TYPE_FPMMap = NULL;

typedef struct {
    FPMMap* map;
    void* ptr;
    size_t size;
} mmap_res;

static void mmap_res_destructor(ErlNifEnv* env, void* obj) {
    mmap_res* res = (mmap_res*)obj;
    if (res->map) {
        fp_mmap_close(res->map);
        res->map = NULL;
    }
}

typedef struct {
    fp_hnsw_index* index;
} hnsw_res;

static void hnsw_res_destructor(ErlNifEnv* env, void* obj) {
    hnsw_res* res = (hnsw_res*)obj;
    if (res->index) {
        fp_hnsw_free(res->index);
        res->index = NULL;
    }
}

// --- QUERY NIF WRAPPERS ---

static ERL_NIF_TERM manual_nif_fp_query_gemv_columnar(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    int dim_int;
    ErlNifUInt64 count, dim;

    if (!enif_get_uint64(env, argv[2], &count)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[3], &dim)) return enif_make_badarg(env);

    if (!enif_get_tuple(env, argv[0], &dim_int, NULL)) return enif_make_badarg(env);
    if ((size_t)dim_int != dim) return enif_make_badarg(env);

    ErlNifBinary query_bin;
    if (!enif_inspect_binary(env, argv[1], &query_bin)) return enif_make_badarg(env);
    if (query_bin.size != dim * 8) return enif_make_badarg(env);

    const double** columns = malloc(dim * sizeof(double*));
    if (!columns) return enif_make_badarg(env);

    const ERL_NIF_TERM* tuple_elements;
    if (!enif_get_tuple(env, argv[0], &dim_int, &tuple_elements)) {
        free(columns);
        return enif_make_badarg(env);
    }

    ErlNifBinary* col_bins = malloc(dim * sizeof(ErlNifBinary));
    if (!col_bins) {
        free(columns);
        return enif_make_badarg(env);
    }

    ErlNifBinary scores_bin;
    if (!enif_alloc_binary(count * 8, &scores_bin)) {
        free(columns);
        free(col_bins);
        return enif_make_badarg(env);
    }

    fp_query_gemv_columnar_f64(
        columns,
        (const double*)query_bin.data,
        (double*)scores_bin.data,
        (size_t)count,
        (size_t)dim
    );

    free(columns);
    free(col_bins);

    return enif_make_binary(env, &scores_bin);
}

static ERL_NIF_TERM manual_nif_fp_query_gemv_columnar_batch(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    int dim_int;
    ErlNifUInt64 batch_count, count, dim;

    if (!enif_get_uint64(env, argv[2], &batch_count)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[3], &count)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[4], &dim)) return enif_make_badarg(env);

    if (!enif_get_tuple(env, argv[0], &dim_int, NULL)) return enif_make_badarg(env);
    if ((size_t)dim_int != dim) return enif_make_badarg(env);

    ErlNifBinary queries_bin;
    if (!enif_inspect_binary(env, argv[1], &queries_bin)) return enif_make_badarg(env);
    if (queries_bin.size != batch_count * dim * 8) return enif_make_badarg(env);
    if (dim > 100000) return enif_make_badarg(env);

    const double** columns = malloc(dim * sizeof(double*));
    if (!columns) return enif_make_badarg(env);

    const ERL_NIF_TERM* tuple_elements;
    if (!enif_get_tuple(env, argv[0], &dim_int, &tuple_elements)) {
        free(columns);
        return enif_make_badarg(env);
    }

    ErlNifBinary* col_bins = malloc(dim * sizeof(ErlNifBinary));
    if (!col_bins) {
        free(columns);
        return enif_make_badarg(env);
    }

    for (size_t d = 0; d < dim; d++) {
        if (!enif_inspect_binary(env, tuple_elements[d], &col_bins[d]) || col_bins[d].size != count * 8) {
            free(columns);
            free(col_bins);
            return enif_make_badarg(env);
        }
        columns[d] = (const double*)col_bins[d].data;
    }

    ErlNifBinary scores_bin;
    if (!enif_alloc_binary(batch_count * count * 8, &scores_bin)) {
        free(columns); free(col_bins); return enif_make_badarg(env);
    }

    fp_query_gemv_columnar_batch_f64(
        columns,
        (const double*)queries_bin.data,
        batch_count,
        (double*)scores_bin.data,
        count,
        dim
    );

    free(columns);
    free(col_bins);

    return enif_make_binary(env, &scores_bin);
}

static ERL_NIF_TERM manual_nif_fp_query_gemv_f32_batch(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    ErlNifUInt64 count, dim;
    ErlNifBinary db_vectors_bin, query_bin;

    if (!enif_inspect_binary(env, argv[0], &db_vectors_bin)) return enif_make_badarg(env);
    if (!enif_inspect_binary(env, argv[1], &query_bin)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[2], &count)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[3], &dim)) return enif_make_badarg(env);

    if (query_bin.size != dim * 4) return enif_make_badarg(env);
    if (db_vectors_bin.size != count * dim * 4) return enif_make_badarg(env);

    ErlNifBinary scores_bin;
    if (!enif_alloc_binary(count * 4, &scores_bin)) return enif_make_badarg(env);

    fp_query_gemv_f32_batch(
        (const float*)db_vectors_bin.data,
        (const float*)query_bin.data,
        (float*)scores_bin.data,
        (size_t)count,
        (size_t)dim
    );

    return enif_make_binary(env, &scores_bin);
}

static ERL_NIF_TERM manual_nif_fp_vector_sum_f32(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    ErlNifUInt64 count, dim;
    ErlNifBinary vectors_bin;

    if (!enif_inspect_binary(env, argv[0], &vectors_bin)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[1], &count)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[2], &dim)) return enif_make_badarg(env);

    // fprintf(stderr, "NIF fp_vector_sum_f32: count=%llu, dim=%llu, bin_size=%zu\\n", 
    //        (unsigned long long)count, (unsigned long long)dim, vectors_bin.size);

    if (vectors_bin.size != count * dim * 4) return enif_make_badarg(env);

    ErlNifBinary output_bin;
    if (!enif_alloc_binary(dim * 4, &output_bin)) return enif_make_badarg(env);

    fp_vector_sum_f32(
        (const float*)vectors_bin.data,
        (float*)output_bin.data,
        (size_t)count,
        (size_t)dim
    );

    return enif_make_binary(env, &output_bin);
}

static ERL_NIF_TERM manual_nif_fp_query_gemv_quantized_f32(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    int dim_int;
    ErlNifUInt64 count, dim;
    double bias_dbl;

    if (!enif_get_double(env, argv[2], &bias_dbl)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[3], &count)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[4], &dim)) return enif_make_badarg(env);

    if (!enif_get_tuple(env, argv[0], &dim_int, NULL)) return enif_make_badarg(env);
    if ((size_t)dim_int != dim) return enif_make_badarg(env);

    ErlNifBinary query_bin;
    if (!enif_inspect_binary(env, argv[1], &query_bin)) return enif_make_badarg(env);
    if (query_bin.size != dim * 4) return enif_make_badarg(env);

    const uint8_t** columns = malloc(dim * sizeof(uint8_t*));
    if (!columns) return enif_make_badarg(env);

    const ERL_NIF_TERM* tuple_elements;
    enif_get_tuple(env, argv[0], &dim_int, &tuple_elements);

    ErlNifBinary* col_bins = malloc(dim * sizeof(ErlNifBinary));
    if (!col_bins) { free(columns); return enif_make_badarg(env); }

    for (size_t d = 0; d < dim; d++) {
        if (!enif_inspect_binary(env, tuple_elements[d], &col_bins[d]) || col_bins[d].size != count) {
            free(columns); free(col_bins); return enif_make_badarg(env);
        }
        columns[d] = (const uint8_t*)col_bins[d].data;
    }

    ErlNifBinary scores_bin;
    if (!enif_alloc_binary(count * 4, &scores_bin)) {
        free(columns); free(col_bins); return enif_make_badarg(env);
    }

    fp_query_gemv_quantized_f32_u8(
        columns,
        (const float*)query_bin.data,
        (float)bias_dbl,
        (float*)scores_bin.data,
        count,
        dim
    );

    free(columns);
    free(col_bins);

    return enif_make_binary(env, &scores_bin);
}

static ERL_NIF_TERM nif_fp_query_gemv_indexed(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    int dim_int;
    ErlNifUInt64 count, dim;

    if (!enif_get_uint64(env, argv[3], &count)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[4], &dim)) return enif_make_badarg(env);

    if (!enif_get_tuple(env, argv[0], &dim_int, NULL)) return enif_make_badarg(env);
    if ((size_t)dim_int != dim) return enif_make_badarg(env);

    ErlNifBinary query_bin;
    if (!enif_inspect_binary(env, argv[1], &query_bin)) return enif_make_badarg(env);
    if (query_bin.size != dim * 8) return enif_make_badarg(env);

    ErlNifBinary indices_bin;
    if (!enif_inspect_binary(env, argv[2], &indices_bin)) return enif_make_badarg(env);
    size_t num_indices = indices_bin.size / 4;

    const double** columns = malloc(dim * sizeof(double*));
    if (!columns) return enif_make_badarg(env);

    const ERL_NIF_TERM* tuple_elements;
    if (!enif_get_tuple(env, argv[0], &dim_int, &tuple_elements)) {
        free(columns);
        return enif_make_badarg(env);
    }

    ErlNifBinary* col_bins = malloc(dim * sizeof(ErlNifBinary));
    if (!col_bins) {
        free(columns);
        return enif_make_badarg(env);
    }

    for (size_t d = 0; d < dim; d++) {
        if (!enif_inspect_binary(env, tuple_elements[d], &col_bins[d])) {
            free(columns);
            free(col_bins);
            return enif_make_badarg(env);
        }
        if (col_bins[d].size != count * 8) {
            free(columns);
            free(col_bins);
            return enif_make_badarg(env);
        }
        columns[d] = (const double*)col_bins[d].data;
    }

    ErlNifBinary scores_bin;
    if (!enif_alloc_binary(num_indices * 8, &scores_bin)) {
        free(columns);
        free(col_bins);
        return enif_make_badarg(env);
    }

    fp_query_gemv_indexed_f64(
        columns,
        (const double*)query_bin.data,
        (const int32_t*)indices_bin.data,
        num_indices,
        (double*)scores_bin.data,
        count,
        dim
    );

    free(columns);
    free(col_bins);

    return enif_make_binary(env, &scores_bin);
}

static ERL_NIF_TERM nif_fp_query_topk(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    ErlNifBinary scores_bin;
    ErlNifUInt64 count, k;
    double threshold;

    if (!enif_inspect_binary(env, argv[0], &scores_bin)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[1], &count)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[2], &k)) return enif_make_badarg(env);
    if (!enif_get_double(env, argv[3], &threshold)) return enif_make_badarg(env);

    if (scores_bin.size != count * 8) return enif_make_badarg(env);

    ErlNifBinary indices_bin, result_scores_bin;
    if (!enif_alloc_binary(k * 4, &indices_bin)) return enif_make_badarg(env);
    if (!enif_alloc_binary(k * 8, &result_scores_bin)) {
        enif_release_binary(&indices_bin);
        return enif_make_badarg(env);
    }

    size_t result_count = fp_query_topk_f64(
        (const double*)scores_bin.data,
        count,
        k,
        threshold,
        (int32_t*)indices_bin.data,
        (double*)result_scores_bin.data
    );

    if (result_count < k) {
        enif_realloc_binary(&indices_bin, result_count * 4);
        enif_realloc_binary(&result_scores_bin, result_count * 8);
    }

    return enif_make_tuple3(env,
        enif_make_uint64(env, result_count),
        enif_make_binary(env, &indices_bin),
        enif_make_binary(env, &result_scores_bin)
    );
}

// --- QUANTIZATION NIF WRAPPERS ---

static ERL_NIF_TERM nif_fp_quantize_f64_to_u8(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    ErlNifBinary in_bin;
    double min_val, inv_scale;

    if (!enif_inspect_binary(env, argv[0], &in_bin)) return enif_make_badarg(env);
    if (!enif_get_double(env, argv[1], &min_val)) return enif_make_badarg(env);
    if (!enif_get_double(env, argv[2], &inv_scale)) return enif_make_badarg(env);

    size_t count = in_bin.size / 8;
    ErlNifBinary out_bin;
    if (!enif_alloc_binary(count, &out_bin)) return enif_make_badarg(env);

    fp_quantize_f64_to_u8((const double*)in_bin.data, (uint8_t*)out_bin.data, count, min_val, inv_scale);

    return enif_make_binary(env, &out_bin);
}

static ERL_NIF_TERM nif_fp_query_gemv_quantized(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    int dim_int;
    ErlNifUInt64 count, dim;
    double bias;

    if (!enif_get_double(env, argv[2], &bias)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[3], &count)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[4], &dim)) return enif_make_badarg(env);

    if (!enif_get_tuple(env, argv[0], &dim_int, NULL)) return enif_make_badarg(env);
    if ((size_t)dim_int != dim) return enif_make_badarg(env);

    ErlNifBinary query_bin;
    if (!enif_inspect_binary(env, argv[1], &query_bin)) return enif_make_badarg(env);
    if (query_bin.size != dim * 8) return enif_make_badarg(env);

    const uint8_t** columns = malloc(dim * sizeof(uint8_t*));
    if (!columns) return enif_make_badarg(env);

    const ERL_NIF_TERM* tuple_elements;
    enif_get_tuple(env, argv[0], &dim_int, &tuple_elements);

    ErlNifBinary* col_bins = malloc(dim * sizeof(ErlNifBinary));
    if (!col_bins) { free(columns); return enif_make_badarg(env); }

    for (size_t d = 0; d < dim; d++) {
        if (!enif_inspect_binary(env, tuple_elements[d], &col_bins[d]) || col_bins[d].size != count) {
            free(columns); free(col_bins); return enif_make_badarg(env);
        }
        columns[d] = (const uint8_t*)col_bins[d].data;
    }

    ErlNifBinary scores_bin;
    if (!enif_alloc_binary(count * 8, &scores_bin)) {
        free(columns); free(col_bins); return enif_make_badarg(env);
    }

    fp_query_gemv_quantized_f64_u8(
        columns,
        (const double*)query_bin.data,
        bias,
        (double*)scores_bin.data,
        count,
        dim
    );

    free(columns);
    free(col_bins);

    return enif_make_binary(env, &scores_bin);
}

static ERL_NIF_TERM nif_fp_sparse_dotp(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    // argv[0]: indices_a, argv[1]: values_a
    // argv[2]: indices_b, argv[3]: values_b

    ErlNifBinary ind_a, val_a, ind_b, val_b;

    if (!enif_inspect_binary(env, argv[0], &ind_a)) return enif_make_badarg(env);
    if (!enif_inspect_binary(env, argv[1], &val_a)) return enif_make_badarg(env);
    if (!enif_inspect_binary(env, argv[2], &ind_b)) return enif_make_badarg(env);
    if (!enif_inspect_binary(env, argv[3], &val_b)) return enif_make_badarg(env);

    size_t len_a = ind_a.size / 4;
    size_t len_b = ind_b.size / 4;

    double dot = fp_sparse_dotp_f64(
        (const int32_t*)ind_a.data,
        (const double*)val_a.data,
        len_a,
        (const int32_t*)ind_b.data,
        (const double*)val_b.data,
        len_b
    );

    return enif_make_double(env, dot);
}

static ERL_NIF_TERM nif_fp_hnsw_create(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    int dim, M, ef_construction;
    ErlNifUInt64 capacity;

    if (!enif_get_int(env, argv[0], &dim)) return enif_make_badarg(env);
    if (!enif_get_int(env, argv[1], &M)) return enif_make_badarg(env);
    if (!enif_get_int(env, argv[2], &ef_construction)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[3], &capacity)) return enif_make_badarg(env);

    hnsw_res* res = enif_alloc_resource(HNSW_RES_TYPE, sizeof(hnsw_res));
    res->index = fp_hnsw_create(dim, M, ef_construction, (size_t)capacity);

    if (!res->index) {
        enif_release_resource(res);
        return enif_make_badarg(env);
    }

    ERL_NIF_TERM term = enif_make_resource(env, res);
    enif_release_resource(res);
    return term;
}

static ERL_NIF_TERM nif_fp_hnsw_insert(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    hnsw_res* res;
    int vector_idx;
    ErlNifBinary vec_bin;
    ErlNifUInt64 db_count;

    if (!enif_get_resource(env, argv[0], HNSW_RES_TYPE, (void**)&res)) return enif_make_badarg(env);
    if (!enif_get_int(env, argv[1], &vector_idx)) return enif_make_badarg(env);
    if (!enif_inspect_binary(env, argv[2], &vec_bin)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[4], &db_count)) return enif_make_badarg(env);

    int dim = res->index->dim;
    if (vec_bin.size != (size_t)dim * 8) return enif_make_badarg(env);

    const double** columns = malloc(dim * sizeof(double*));
    if (!columns) return enif_make_badarg(env);

    int dim_int;
    const ERL_NIF_TERM* tuple_elements;
    if (!enif_get_tuple(env, argv[3], &dim_int, &tuple_elements) || dim_int != dim) {
        free(columns);
        return enif_make_badarg(env);
    }
    
    ErlNifBinary* col_bins = malloc(dim * sizeof(ErlNifBinary));
    if (!col_bins) {
        free(columns);
        return enif_make_badarg(env);
    }

    double** converted_columns = NULL;

    for (int d = 0; d < dim; d++) {
        if (!enif_inspect_binary(env, tuple_elements[d], &col_bins[d])) {
            // Free everything before returning
            if (converted_columns) {
                for (int j = 0; j < d; j++) if (converted_columns[j]) free(converted_columns[j]);
                free(converted_columns);
            }
            free(columns);
            free(col_bins);
            return enif_make_badarg(env);
        }

        if (col_bins[d].size == db_count * 4) {
            // f32 detected
            if (converted_columns == NULL) {
                converted_columns = calloc(dim, sizeof(double*));
                if (!converted_columns) { free(columns); free(col_bins); return enif_make_badarg(env); }
            }
            converted_columns[d] = malloc(db_count * sizeof(double));
            if (!converted_columns[d]) {
                for (int j = 0; j < d; j++) if (converted_columns[j]) free(converted_columns[j]);
                free(converted_columns); free(columns); free(col_bins); return enif_make_badarg(env);
            }
            float* src = (float*)col_bins[d].data;
            for (size_t i = 0; i < db_count; i++) {
                converted_columns[d][i] = (double)src[i];
            }
            columns[d] = converted_columns[d];
        } else if (col_bins[d].size == db_count * 8) {
            columns[d] = (const double*)col_bins[d].data;
        } else {
            if (converted_columns) {
                for (int j = 0; j < d; j++) if (converted_columns[j]) free(converted_columns[j]);
                free(converted_columns);
            }
            free(columns); free(col_bins); return enif_make_badarg(env);
        }
    }

    fp_hnsw_insert(res->index, vector_idx, (const double*)vec_bin.data, columns, (size_t)db_count);

    if (converted_columns) {
        for (int d = 0; d < dim; d++) {
            if (converted_columns[d]) free(converted_columns[d]);
        }
        free(converted_columns);
    }
    free(columns);
    free(col_bins);

    return enif_make_atom(env, "ok");
}

static ERL_NIF_TERM nif_fp_hnsw_search(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    hnsw_res* res;
    ErlNifBinary query_bin;
    int k, ef_search;
    ErlNifUInt64 db_count;

    if (!enif_get_resource(env, argv[0], HNSW_RES_TYPE, (void**)&res)) return enif_make_badarg(env);
    if (!enif_inspect_binary(env, argv[1], &query_bin)) return enif_make_badarg(env);
    if (!enif_get_int(env, argv[2], &k)) return enif_make_badarg(env);
    if (!enif_get_int(env, argv[3], &ef_search)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[5], &db_count)) return enif_make_badarg(env);

    int dim = res->index->dim;
    if (query_bin.size != (size_t)dim * 8) return enif_make_badarg(env);

    const double** columns = malloc(dim * sizeof(double*));
    if (!columns) return enif_make_badarg(env);

    int dim_int;
    const ERL_NIF_TERM* tuple_elements;
    if (!enif_get_tuple(env, argv[4], &dim_int, &tuple_elements) || dim_int != dim) {
        free(columns);
        return enif_make_badarg(env);
    }
    
    ErlNifBinary* col_bins = malloc(dim * sizeof(ErlNifBinary));
    if (!col_bins) {
        free(columns);
        return enif_make_badarg(env);
    }

    double** converted_columns = NULL;

    for (int d = 0; d < dim; d++) {
        if (!enif_inspect_binary(env, tuple_elements[d], &col_bins[d])) {
            if (converted_columns) {
                for (int j = 0; j < d; j++) if (converted_columns[j]) free(converted_columns[j]);
                free(converted_columns);
            }
            free(columns); free(col_bins); return enif_make_badarg(env);
        }

        if (col_bins[d].size == db_count * 4) {
            // f32 detected
            if (converted_columns == NULL) {
                converted_columns = calloc(dim, sizeof(double*));
                if (!converted_columns) { free(columns); free(col_bins); return enif_make_badarg(env); }
            }
            converted_columns[d] = malloc(db_count * sizeof(double));
            if (!converted_columns[d]) {
                for (int j = 0; j < d; j++) if (converted_columns[j]) free(converted_columns[j]);
                free(converted_columns); free(columns); free(col_bins); return enif_make_badarg(env);
            }
            float* src = (float*)col_bins[d].data;
            for (size_t i = 0; i < db_count; i++) {
                converted_columns[d][i] = (double)src[i];
            }
            columns[d] = converted_columns[d];
        } else if (col_bins[d].size == db_count * 8) {
            columns[d] = (const double*)col_bins[d].data;
        } else {
            if (converted_columns) {
                for (int j = 0; j < d; j++) if (converted_columns[j]) free(converted_columns[j]);
                free(converted_columns);
            }
            free(columns); free(col_bins); return enif_make_badarg(env);
        }
    }

    int32_t* results_indices = malloc(k * sizeof(int32_t));
    double* results_scores = malloc(k * sizeof(double));

    if (!results_indices || !results_scores) {
        if (results_indices) free(results_indices);
        if (results_scores) free(results_scores);
        if (converted_columns) {
            for (int d = 0; d < dim; d++) if (converted_columns[d]) free(converted_columns[d]);
            free(converted_columns);
        }
        free(columns); free(col_bins); return enif_make_badarg(env);
    }

    size_t result_count = fp_hnsw_search(
        res->index,
        (const double*)query_bin.data,
        k,
        ef_search,
        columns,
        (size_t)db_count,
        results_indices,
        results_scores
    );

    if (converted_columns) {
        for (int d = 0; d < dim; d++) {
            if (converted_columns[d]) free(converted_columns[d]);
        }
        free(converted_columns);
    }
    free(columns);
    free(col_bins);

    ErlNifBinary indices_bin, scores_bin;
    enif_alloc_binary(result_count * 4, &indices_bin);
    memcpy(indices_bin.data, results_indices, result_count * 4);
    
    enif_alloc_binary(result_count * 8, &scores_bin);
    memcpy(scores_bin.data, results_scores, result_count * 8);

    free(results_indices);
    free(results_scores);

    return enif_make_tuple3(env,
        enif_make_uint64(env, result_count),
        enif_make_binary(env, &indices_bin),
        enif_make_binary(env, &scores_bin)
    );
}

// --- MMAP NIFS ---

static ERL_NIF_TERM manual_nif_fp_mmap_open(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    char path[1024];
    ErlNifBinary bin;
    
    if (enif_inspect_binary(env, argv[0], &bin)) {
        if (bin.size >= sizeof(path)) return enif_make_badarg(env);
        memcpy(path, bin.data, bin.size);
        path[bin.size] = '\0';
    } else if (enif_get_string(env, argv[0], path, sizeof(path), ERL_NIF_LATIN1) < 1) {
        return enif_make_badarg(env);
    }

    // fprintf(stderr, "NIF mmap open: %s\n", path);

    mmap_res* res = enif_alloc_resource(RES_TYPE_FPMMap, sizeof(mmap_res));
    res->map = fp_mmap_open_read(path, &res->ptr, &res->size);

    if (!res->map) {
        enif_release_resource(res);
        return enif_make_tuple2(env, enif_make_atom(env, "error"), enif_make_atom(env, "failed_to_map"));
    }

    ERL_NIF_TERM term = enif_make_resource(env, res);
    enif_release_resource(res);
    // return term; (Removed early return)
    return enif_make_tuple2(env, enif_make_atom(env, "ok"), term);
}

static ERL_NIF_TERM manual_nif_fp_query_gemv_mmap_f32(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    int dim_int;
    ErlNifUInt64 count, dim;

    // Args: mmap_resources_tuple, query_bin, count, dim
    if (!enif_get_uint64(env, argv[2], &count)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[3], &dim)) return enif_make_badarg(env);

    if (!enif_get_tuple(env, argv[0], &dim_int, NULL)) return enif_make_badarg(env);
    if ((size_t)dim_int != dim) return enif_make_badarg(env);

    ErlNifBinary query_bin;
    if (!enif_inspect_binary(env, argv[1], &query_bin)) return enif_make_badarg(env);
    if (query_bin.size != dim * 4) return enif_make_badarg(env);

    // Extract pointers from mmap resources
    const float** columns = malloc(dim * sizeof(float*));
    if (!columns) return enif_make_badarg(env);

    const ERL_NIF_TERM* tuple_elements;
    if (!enif_get_tuple(env, argv[0], &dim_int, &tuple_elements)) {
        free(columns);
        return enif_make_badarg(env);
    }


    for (size_t d = 0; d < dim; d++) {
        mmap_res* res;
        if (!enif_get_resource(env, tuple_elements[d], RES_TYPE_FPMMap, (void**)&res)) {
            free(columns);
            return enif_make_badarg(env);
        }
        // Safety check: ensure size is enough
        if (res->size < count * 4) {
             free(columns);
             return enif_make_badarg(env); // File too small
        }
        columns[d] = (const float*)res->ptr;
    }

    ErlNifBinary scores_bin;
    if (!enif_alloc_binary(count * 4, &scores_bin)) {
        free(columns);
        return enif_make_badarg(env);
    }

    fp_query_gemv_columnar_f32(
        columns,
        (const float*)query_bin.data,
        (float*)scores_bin.data,
        count,
        dim
    );
    
    free(columns);
    return enif_make_binary(env, &scores_bin);
}

static ERL_NIF_TERM manual_nif_fp_query_gemv_bitmasked_f32(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    int dim_int;
    ErlNifUInt64 count, dim;
    ErlNifBinary query_bin, bitmap_bin;

    if (argc != 5) return enif_make_badarg(env);

    if (!enif_get_uint64(env, argv[3], &count)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[4], &dim)) return enif_make_badarg(env);

    if (!enif_get_tuple(env, argv[0], &dim_int, NULL)) return enif_make_badarg(env);
    if ((size_t)dim_int != (size_t)dim) return enif_make_badarg(env);

    if (!enif_inspect_binary(env, argv[1], &query_bin)) return enif_make_badarg(env);
    if (query_bin.size != dim * 4) return enif_make_badarg(env);

    if (!enif_inspect_binary(env, argv[2], &bitmap_bin)) return enif_make_badarg(env);
    
    size_t expected_bitmap_bytes = ((count + 63) / 64) * 8;
    if (bitmap_bin.size < expected_bitmap_bytes) return enif_make_badarg(env);

    const ERL_NIF_TERM* tuple_elements;
    if (!enif_get_tuple(env, argv[0], &dim_int, &tuple_elements)) return enif_make_badarg(env);

    const float** columns = malloc(dim * sizeof(float*));
    if (!columns) return enif_make_badarg(env);

    ErlNifBinary* col_bins = malloc(dim * sizeof(ErlNifBinary));
    if (!col_bins) { free(columns); return enif_make_badarg(env); }

    for (size_t d = 0; d < dim; d++) {
        if (!enif_inspect_binary(env, tuple_elements[d], &col_bins[d]) || col_bins[d].size < count * 4) {
            free(columns); free(col_bins); return enif_make_badarg(env);
        }
        columns[d] = (const float*)col_bins[d].data;
    }

    ErlNifBinary scores_bin;
    if (!enif_alloc_binary(count * 4, &scores_bin)) {
        free(columns); free(col_bins); return enif_make_badarg(env);
    }

    fp_query_gemv_bitmasked_f32(
        columns,
        (const float*)query_bin.data,
        (const uint64_t*)bitmap_bin.data,
        (float*)scores_bin.data,
        count,
        dim
    );

    free(columns);
    free(col_bins);

    return enif_make_binary(env, &scores_bin);
}

// --- BITMAP NIFS (Functional/Immutable) ---

static ERL_NIF_TERM manual_nif_fp_bitmap_set(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    ErlNifBinary in_bin;
    ErlNifUInt64 index;

    if (!enif_inspect_binary(env, argv[0], &in_bin)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[1], &index)) return enif_make_badarg(env);

    // FP Principle: Immutability. We cannot modify in_bin.data in place.
    // We must allocate a new binary (Copy-on-Write).
    
    // Check if index is within bounds of the *current* binary size.
    // If input is empty or too small, we might need to resize (reallocate larger).
    // For simplicity in this kernel, we assume the user manages size or we resize if needed.
    // Let's assume resize logic: required bytes = (index / 64 + 1) * 8.
    
    size_t required_bytes = ((index / 64) + 1) * 8;
    size_t new_size = (in_bin.size > required_bytes) ? in_bin.size : required_bytes;

    ErlNifBinary out_bin;
    if (!enif_alloc_binary(new_size, &out_bin)) return enif_make_badarg(env);

    // 1. Copy existing data (Copy)
    // Initialize new space to 0 if we grew
    memset(out_bin.data, 0, new_size);
    if (in_bin.size > 0) {
        memcpy(out_bin.data, in_bin.data, in_bin.size);
    }

    // 2. Mutate the NEW copy (Write)
    fp_bitmap_set((uint64_t*)out_bin.data, (size_t)index);

    // 3. Return new value (Immutable output)
    return enif_make_binary(env, &out_bin);
}

static ERL_NIF_TERM manual_nif_fp_bitmap_and(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    ErlNifBinary a_bin, b_bin;

    if (!enif_inspect_binary(env, argv[0], &a_bin)) return enif_make_badarg(env);
    if (!enif_inspect_binary(env, argv[1], &b_bin)) return enif_make_badarg(env);

    size_t size = (a_bin.size < b_bin.size) ? a_bin.size : b_bin.size;
    ErlNifBinary out_bin;
    if (!enif_alloc_binary(size, &out_bin)) return enif_make_badarg(env);

    size_t n_u64 = size / 8;
    fp_bitmap_and((const uint64_t*)a_bin.data, (const uint64_t*)b_bin.data, (uint64_t*)out_bin.data, n_u64);

    return enif_make_binary(env, &out_bin);
}

static ERL_NIF_TERM nif_fp_pca_transform_result(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    PCAResult* res;
    ErlNifBinary data_bin;
    int count;

    if (!enif_get_resource(env, argv[0], RES_TYPE_PCAResult, (void**)&res)) return enif_make_badarg(env);
    if (!enif_inspect_binary(env, argv[1], &data_bin)) return enif_make_badarg(env);
    if (!enif_get_int(env, argv[2], &count)) return enif_make_badarg(env);
    if (count <= 0) return enif_make_badarg(env);

    int d = res->model.n_features;
    int k = res->model.n_components;
    size_t expected_in = (size_t)count * (size_t)d * sizeof(double);
    if (data_bin.size != expected_in) return enif_make_badarg(env);

    ErlNifBinary out_bin;
    if (!enif_alloc_binary((size_t)count * (size_t)k * sizeof(double), &out_bin)) return enif_make_badarg(env);

    fp_pca_transform(&res->model, (const double*)data_bin.data, (double*)out_bin.data, count);

    return enif_make_binary(env, &out_bin);
}

static ERL_NIF_TERM nif_fp_pca_result_n_components(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    PCAResult* res;
    if (!enif_get_resource(env, argv[0], RES_TYPE_PCAResult, (void**)&res)) return enif_make_badarg(env);
    return enif_make_int(env, res->model.n_components);
}

static ERL_NIF_TERM nif_fp_pca_result_total_variance(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    PCAResult* res;
    if (!enif_get_resource(env, argv[0], RES_TYPE_PCAResult, (void**)&res)) return enif_make_badarg(env);
    return enif_make_double(env, res->model.total_variance);
}

static ERL_NIF_TERM nif_fp_pca_result_explained_variance(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    PCAResult* res;
    ErlNifUInt64 size;

    if (!enif_get_resource(env, argv[0], RES_TYPE_PCAResult, (void**)&res)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[1], &size)) return enif_make_badarg(env);

    size_t expected = (size_t)res->model.n_components * sizeof(double);
    if (size > expected || res->model.explained_variance_ratio == NULL) return enif_make_badarg(env);

    ErlNifBinary out_bin;
    if (!enif_alloc_binary((size_t)size, &out_bin)) return enif_make_badarg(env);
    memcpy(out_bin.data, res->model.explained_variance_ratio, (size_t)size);

    return enif_make_binary(env, &out_bin);
}

static ERL_NIF_TERM nif_fp_pca_result_cumulative_variance(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    PCAResult* res;
    ErlNifUInt64 size;

    if (!enif_get_resource(env, argv[0], RES_TYPE_PCAResult, (void**)&res)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[1], &size)) return enif_make_badarg(env);

    size_t expected = (size_t)res->model.n_components * sizeof(double);
    if (size > expected || res->model.cumulative_variance_ratio == NULL) return enif_make_badarg(env);

    ErlNifBinary out_bin;
    if (!enif_alloc_binary((size_t)size, &out_bin)) return enif_make_badarg(env);
    memcpy(out_bin.data, res->model.cumulative_variance_ratio, (size_t)size);

    return enif_make_binary(env, &out_bin);
}

// --- BLAKE3 NIF WRAPPER ---

static ERL_NIF_TERM nif_fp_blake3_hash(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    ErlNifBinary input_bin;
    if (!enif_inspect_binary(env, argv[0], &input_bin)) return enif_make_badarg(env);

    ErlNifBinary output_bin;
    if (!enif_alloc_binary(32, &output_bin)) return enif_make_badarg(env);

    fp_blake3_hash(input_bin.data, input_bin.size, output_bin.data);

    return enif_make_binary(env, &output_bin);
}

static ERL_NIF_TERM nif_fp_quantize_f32_to_u8(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    ErlNifBinary in_bin;
    double min_val, inv_scale;

    if (!enif_inspect_binary(env, argv[0], &in_bin)) return enif_make_badarg(env);
    if (!enif_get_double(env, argv[1], &min_val)) return enif_make_badarg(env);
    if (!enif_get_double(env, argv[2], &inv_scale)) return enif_make_badarg(env);

    size_t count = in_bin.size / 4;
    ErlNifBinary out_bin;
    if (!enif_alloc_binary(count, &out_bin)) return enif_make_badarg(env);

    fp_quantize_f32_to_u8((const float*)in_bin.data, (uint8_t*)out_bin.data, count, (float)min_val, (float)inv_scale);

    return enif_make_binary(env, &out_bin);
}

// --- LIFECYCLE ---

static int load(ErlNifEnv* env, void** priv_data, ERL_NIF_TERM load_info);
static void unload(ErlNifEnv* env, void* priv_data);

static int load(ErlNifEnv* env, void** priv_data, ERL_NIF_TERM load_info) {
    fprintf(stderr, "NIF LOADING...\n");
    // Initialize HNSW resource type
    HNSW_RES_TYPE = enif_open_resource_type(env, NULL, "hnsw_index", hnsw_res_destructor, ERL_NIF_RT_CREATE, NULL);
    RES_TYPE_FPMMap = enif_open_resource_type(env, NULL, "FPMMap", mmap_res_destructor, ERL_NIF_RT_CREATE, NULL);
    
    // Initialize Job system resources
    if (fp_job_load(env) != 0) {
        return -1;
    }

    return load_resources(env, priv_data, load_info);
}

static void unload(ErlNifEnv* env, void* priv_data) {
    (void)priv_data;
    fp_job_unload(env);
}

static int upgrade(ErlNifEnv* env, void** priv_data, void** old_priv_data, ERL_NIF_TERM load_info) {
    return 0;
}

ERL_NIF_INIT(Elixir.MerkleDb.ASM, generated_nif_funcs, load, NULL, upgrade, unload)
