#include <string.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

// --- GCC 14/15 COMPATIBILITY HACK ---
#ifdef __GNUC__
  #define _SAVED_GNUC_ __GNUC__
  #undef __GNUC__
#endif

#include <erl_nif.h>

#ifdef _SAVED_GNUC_
  #define __GNUC__ _SAVED_GNUC_
  #undef _SAVED_GNUC_
#endif

// --- INCLUDE QUERY KERNEL ---
#include "fp_lib/include/fp_query.h"

// --- INCLUDE BLAKE3 ---
#include "fp_lib/include/fp_blake3.h"

// --- INCLUDE THE AUTOMATICALLY GENERATED NIF IMPLEMENTATION ---
// This file is generated by 'mix run gen_bridge.exs' and contains
// all the nif_fp_* wrapper functions and the generated_nif_funcs array.
#include "generated_nif.c"

// --- QUERY NIF WRAPPERS ---

static ERL_NIF_TERM nif_fp_query_gemv_columnar(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    int dim_int;
    ErlNifUInt64 count, dim;

    if (!enif_get_uint64(env, argv[2], &count)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[3], &dim)) return enif_make_badarg(env);

    if (!enif_get_tuple(env, argv[0], &dim_int, NULL)) return enif_make_badarg(env);
    if ((size_t)dim_int != dim) return enif_make_badarg(env);

    ErlNifBinary query_bin;
    if (!enif_inspect_binary(env, argv[1], &query_bin)) return enif_make_badarg(env);
    if (query_bin.size != dim * 8) return enif_make_badarg(env);

    const double** columns = malloc(dim * sizeof(double*));
    if (!columns) return enif_make_badarg(env);

    const ERL_NIF_TERM* tuple_elements;
    if (!enif_get_tuple(env, argv[0], &dim_int, &tuple_elements)) {
        free(columns);
        return enif_make_badarg(env);
    }

    ErlNifBinary* col_bins = malloc(dim * sizeof(ErlNifBinary));
    if (!col_bins) {
        free(columns);
        return enif_make_badarg(env);
    }

    for (size_t d = 0; d < dim; d++) {
        if (!enif_inspect_binary(env, tuple_elements[d], &col_bins[d])) {
            free(columns);
            free(col_bins);
            return enif_make_badarg(env);
        }
        if (col_bins[d].size != count * 8) {
            free(columns);
            free(col_bins);
            return enif_make_badarg(env);
        }
        columns[d] = (const double*)col_bins[d].data;
    }

    ErlNifBinary scores_bin;
    if (!enif_alloc_binary(count * 8, &scores_bin)) {
        free(columns);
        free(col_bins);
        return enif_make_badarg(env);
    }

    fp_query_gemv_columnar_f64(
        columns,
        (const double*)query_bin.data,
        (double*)scores_bin.data,
        count,
        dim
    );

    free(columns);
    free(col_bins);

    return enif_make_binary(env, &scores_bin);
}

static ERL_NIF_TERM nif_fp_query_gemv_indexed(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    // argv[0]: columns tuple
    // argv[1]: query binary
    // argv[2]: indices binary (int32 array)
    // argv[3]: count (total vectors)
    // argv[4]: dim

    int dim_int;
    ErlNifUInt64 count, dim;

    if (!enif_get_uint64(env, argv[3], &count)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[4], &dim)) return enif_make_badarg(env);

    if (!enif_get_tuple(env, argv[0], &dim_int, NULL)) return enif_make_badarg(env);
    if ((size_t)dim_int != dim) return enif_make_badarg(env);

    ErlNifBinary query_bin;
    if (!enif_inspect_binary(env, argv[1], &query_bin)) return enif_make_badarg(env);
    if (query_bin.size != dim * 8) return enif_make_badarg(env);

    ErlNifBinary indices_bin;
    if (!enif_inspect_binary(env, argv[2], &indices_bin)) return enif_make_badarg(env);
    size_t num_indices = indices_bin.size / 4;  // int32 = 4 bytes

    const double** columns = malloc(dim * sizeof(double*));
    if (!columns) return enif_make_badarg(env);

    const ERL_NIF_TERM* tuple_elements;
    if (!enif_get_tuple(env, argv[0], &dim_int, &tuple_elements)) {
        free(columns);
        return enif_make_badarg(env);
    }

    ErlNifBinary* col_bins = malloc(dim * sizeof(ErlNifBinary));
    if (!col_bins) {
        free(columns);
        return enif_make_badarg(env);
    }

    for (size_t d = 0; d < dim; d++) {
        if (!enif_inspect_binary(env, tuple_elements[d], &col_bins[d])) {
            free(columns);
            free(col_bins);
            return enif_make_badarg(env);
        }
        if (col_bins[d].size != count * 8) {
            free(columns);
            free(col_bins);
            return enif_make_badarg(env);
        }
        columns[d] = (const double*)col_bins[d].data;
    }

    // Allocate output: one score per candidate index
    ErlNifBinary scores_bin;
    if (!enif_alloc_binary(num_indices * 8, &scores_bin)) {
        free(columns);
        free(col_bins);
        return enif_make_badarg(env);
    }

    fp_query_gemv_indexed_f64(
        columns,
        (const double*)query_bin.data,
        (const int32_t*)indices_bin.data,
        num_indices,
        (double*)scores_bin.data,
        count,
        dim
    );

    free(columns);
    free(col_bins);

    return enif_make_binary(env, &scores_bin);
}

static ERL_NIF_TERM nif_fp_query_topk(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    ErlNifBinary scores_bin;
    ErlNifUInt64 count, k;
    double threshold;

    if (!enif_inspect_binary(env, argv[0], &scores_bin)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[1], &count)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[2], &k)) return enif_make_badarg(env);
    if (!enif_get_double(env, argv[3], &threshold)) return enif_make_badarg(env);

    if (scores_bin.size != count * 8) return enif_make_badarg(env);

    ErlNifBinary indices_bin, result_scores_bin;
    if (!enif_alloc_binary(k * 4, &indices_bin)) return enif_make_badarg(env);
    if (!enif_alloc_binary(k * 8, &result_scores_bin)) {
        enif_release_binary(&indices_bin);
        return enif_make_badarg(env);
    }

    size_t result_count = fp_query_topk_f64(
        (const double*)scores_bin.data,
        count,
        k,
        threshold,
        (int32_t*)indices_bin.data,
        (double*)result_scores_bin.data
    );

    if (result_count < k) {
        enif_realloc_binary(&indices_bin, result_count * 4);
        enif_realloc_binary(&result_scores_bin, result_count * 8);
    }

    return enif_make_tuple3(env,
        enif_make_uint64(env, result_count),
        enif_make_binary(env, &indices_bin),
        enif_make_binary(env, &result_scores_bin)
    );
}

// --- QUANTIZATION NIF WRAPPERS ---

static ERL_NIF_TERM nif_fp_quantize_f64_to_u8(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    ErlNifBinary in_bin;
    double min_val, inv_scale;

    if (!enif_inspect_binary(env, argv[0], &in_bin)) return enif_make_badarg(env);
    if (!enif_get_double(env, argv[1], &min_val)) return enif_make_badarg(env);
    if (!enif_get_double(env, argv[2], &inv_scale)) return enif_make_badarg(env);

    size_t count = in_bin.size / 8;
    ErlNifBinary out_bin;
    if (!enif_alloc_binary(count, &out_bin)) return enif_make_badarg(env);

    fp_quantize_f64_to_u8((const double*)in_bin.data, (uint8_t*)out_bin.data, count, min_val, inv_scale);

    return enif_make_binary(env, &out_bin);
}

static ERL_NIF_TERM nif_fp_query_gemv_quantized(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    // argv[0]: columns tuple (binaries of u8)
    // argv[1]: scaled query binary (f64)
    // argv[2]: bias (double)
    // argv[3]: count (u64)
    // argv[4]: dim (u64)

    int dim_int;
    ErlNifUInt64 count, dim;
    double bias;

    if (!enif_get_double(env, argv[2], &bias)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[3], &count)) return enif_make_badarg(env);
    if (!enif_get_uint64(env, argv[4], &dim)) return enif_make_badarg(env);

    if (!enif_get_tuple(env, argv[0], &dim_int, NULL)) return enif_make_badarg(env);
    if ((size_t)dim_int != dim) return enif_make_badarg(env);

    ErlNifBinary query_bin;
    if (!enif_inspect_binary(env, argv[1], &query_bin)) return enif_make_badarg(env);
    if (query_bin.size != dim * 8) return enif_make_badarg(env);

    const uint8_t** columns = malloc(dim * sizeof(uint8_t*));
    if (!columns) return enif_make_badarg(env);

    const ERL_NIF_TERM* tuple_elements;
    enif_get_tuple(env, argv[0], &dim_int, &tuple_elements);

    ErlNifBinary* col_bins = malloc(dim * sizeof(ErlNifBinary));
    if (!col_bins) { free(columns); return enif_make_badarg(env); }

    for (size_t d = 0; d < dim; d++) {
        if (!enif_inspect_binary(env, tuple_elements[d], &col_bins[d]) || col_bins[d].size != count) {
            free(columns); free(col_bins); return enif_make_badarg(env);
        }
        columns[d] = (const uint8_t*)col_bins[d].data;
    }

    ErlNifBinary scores_bin;
    if (!enif_alloc_binary(count * 8, &scores_bin)) {
        free(columns); free(col_bins); return enif_make_badarg(env);
    }

    fp_query_gemv_quantized_f64_u8(
        columns,
        (const double*)query_bin.data,
        bias,
        (double*)scores_bin.data,
        count,
        dim
    );

    free(columns);
    free(col_bins);

    return enif_make_binary(env, &scores_bin);
}

// --- BLAKE3 NIF WRAPPER ---

static ERL_NIF_TERM nif_fp_blake3_hash(ErlNifEnv* env, int argc, const ERL_NIF_TERM argv[]) {
    ErlNifBinary input_bin;
    if (!enif_inspect_binary(env, argv[0], &input_bin)) return enif_make_badarg(env);

    ErlNifBinary output_bin;
    if (!enif_alloc_binary(32, &output_bin)) return enif_make_badarg(env);

    fp_blake3_hash(input_bin.data, input_bin.size, output_bin.data);

    return enif_make_binary(env, &output_bin);
}

// Combined function table
static ErlNifFunc all_nif_funcs[] = {
    // Query functions
    {"fp_query_gemv_columnar", 4, nif_fp_query_gemv_columnar, ERL_NIF_DIRTY_JOB_CPU_BOUND},
    {"fp_query_gemv_indexed", 5, nif_fp_query_gemv_indexed, ERL_NIF_DIRTY_JOB_CPU_BOUND},
    {"fp_query_topk", 4, nif_fp_query_topk, 0},
    // Quantization
    {"fp_quantize_f64_to_u8", 3, nif_fp_quantize_f64_to_u8, ERL_NIF_DIRTY_JOB_CPU_BOUND},
    {"fp_query_gemv_quantized", 5, nif_fp_query_gemv_quantized, ERL_NIF_DIRTY_JOB_CPU_BOUND},
    // Blake3
    {"fp_blake3_hash", 1, nif_fp_blake3_hash, 0},
};

// --- LIFECYCLE ---

static int load(ErlNifEnv* env, void** priv_data, ERL_NIF_TERM load_info) {
    return load_resources(env, priv_data, load_info);
}

// Combine generated funcs with query funcs
#define GENERATED_FUNC_COUNT (sizeof(generated_nif_funcs) / sizeof(ErlNifFunc))
#define QUERY_FUNC_COUNT (sizeof(all_nif_funcs) / sizeof(ErlNifFunc))

static ErlNifFunc combined_nif_funcs[GENERATED_FUNC_COUNT + QUERY_FUNC_COUNT];

static int upgrade(ErlNifEnv* env, void** priv_data, void** old_priv_data, ERL_NIF_TERM load_info) {
    return 0;
}

static void unload(ErlNifEnv* env, void* priv_data) {
}

// Build combined table at compile time is tricky, use init
__attribute__((constructor))
static void init_combined_funcs(void) {
    memcpy(combined_nif_funcs, generated_nif_funcs, sizeof(generated_nif_funcs));
    memcpy(combined_nif_funcs + GENERATED_FUNC_COUNT, all_nif_funcs, sizeof(all_nif_funcs));
}

ERL_NIF_INIT(Elixir.MerkleDb.ASM, combined_nif_funcs, load, NULL, upgrade, unload)
